services:
  db:
    image: postgres:15
    container_name: postgres-staging
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata-staging:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: chniha03/backend-app:latest
    container_name: backend-staging
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/appdb
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: chniha03/frontend-app:latest
    container_name: frontend-staging
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata-staging:

networks:
  app-network:
    driver: bridge
